In [42]:
import pandas as pd
import json
import requests
from bs4 import BeautifulSoup
import time
import random

In [43]:
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36'}

In [44]:
url_basica="https://www.lamudi.com.mx/distrito-federal/casa/for-sale/"
paginacion="?page="

In [45]:
 oferta=[]
precios=[]
for i in range(1, 4):
    response = requests.get(url_basica+paginacion+str(i), headers=headers)
    time.sleep(random.randint(1, 3))
    soup = BeautifulSoup(response.text, "html.parser")
    elements=soup.find_all("div", class_="listing listing-card item")
    for elem in elements:
        try:
            oferta.append(elem.find("div", class_="listing-card__title").text)
        except:
            oferta.append(None)

        try:
            precios.append(elem.find("div", class_="price").text)
        except:
            precios.append(None)

In [46]:
#Crear dataframe
lamudi=pd.DataFrame({"oferta":oferta,"precio":precios,"fuente":"lamudi"})
lamudi

,oferta,precio,fuente
0,\n Pirineos 84 Portales...,"\nDesde $ 5,750,000 MXN\n",lamudi
1,\n Agustin Gutierrez 5...,"\nDesde $ 110,893,030 MXN\n",lamudi
2,\n Casa en Venta en Coa...,"\n$ 2,030,000 MXN\n",lamudi
3,\n Casa en Condominio e...,"\n$ 1,350,000 MXN\n",lamudi
4,\n Casa en Venta en Jar...,"\n$ 67,000,000 MXN\n",lamudi
...,...,...,...
87,\n Casa en Venta en San...,"\n$ 9,600,000 MXN\n",lamudi
88,\n Casa en Venta en Bos...,"\n$ 19,950,000 MXN\n",lamudi
89,\n Casa en Venta en San...,"\n$ 13,700,000 MXN\n",lamudi
90,\n Casa en Venta en Sta...,"\n$ 21,382,700 MXN\n",lamudi
91,\n Casa en Venta en Pol...,"\n$ 10,900,000 MXN\n",lamudi